# Generated by Django 2.1.4 on 2018-12-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='score',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
